[models.chat]
identifier = "ollama_chat/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.embedding]
identifier = "ollama/snowflake-arctic-embed2"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.function_calling]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.long_context]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.question_answering]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.rag]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.summarization]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.text_classification]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.text_extraction]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"

[models.thinking]
identifier = "ollama/granite3.2:2b"
provider = "ollama"
api_base = "http://localhost:11434/"
